// Centralized prompt management for coordination agents
// Allows easy switching between different prompt strategies

import {
	WER_FOCUSED_SEGMENT_ANALYSIS_PROMPT,
	WER_FOCUSED_ENHANCED_ANALYSIS_PROMPT,
	WER_FOCUSED_MULTI_SEGMENT_ANALYSIS_PROMPT,
	WER_FOCUSED_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} from './wer_focused_analysis';

import {
	LEGACY_SEGMENT_ANALYSIS_PROMPT,
	LEGACY_ENHANCED_ANALYSIS_PROMPT,
	LEGACY_MULTI_SEGMENT_ANALYSIS_PROMPT,
	LEGACY_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} from './legacy_analysis';

import {
	NO_SECONDARY_ASR_SEGMENT_ANALYSIS_PROMPT,
	NO_SECONDARY_ASR_ENHANCED_ANALYSIS_PROMPT,
	NO_SECONDARY_ASR_MULTI_SEGMENT_ANALYSIS_PROMPT,
	NO_SECONDARY_ASR_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} from './no_secondary_asr_analysis';

export type PromptStrategy = 'wer_focused' | 'legacy' | 'no_secondary_asr';

export interface PromptSet {
	SEGMENT_ANALYSIS_PROMPT: string;
	ENHANCED_ANALYSIS_PROMPT: string;
	MULTI_SEGMENT_ANALYSIS_PROMPT: string;
	MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT: string;
}

const PROMPT_STRATEGIES: Record<PromptStrategy, PromptSet> = {
	wer_focused: {
		SEGMENT_ANALYSIS_PROMPT: WER_FOCUSED_SEGMENT_ANALYSIS_PROMPT,
		ENHANCED_ANALYSIS_PROMPT: WER_FOCUSED_ENHANCED_ANALYSIS_PROMPT,
		MULTI_SEGMENT_ANALYSIS_PROMPT: WER_FOCUSED_MULTI_SEGMENT_ANALYSIS_PROMPT,
		MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT: WER_FOCUSED_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
	},
	legacy: {
		SEGMENT_ANALYSIS_PROMPT: LEGACY_SEGMENT_ANALYSIS_PROMPT,
		ENHANCED_ANALYSIS_PROMPT: LEGACY_ENHANCED_ANALYSIS_PROMPT,
		MULTI_SEGMENT_ANALYSIS_PROMPT: LEGACY_MULTI_SEGMENT_ANALYSIS_PROMPT,
		MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT: LEGACY_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
	},
	no_secondary_asr: {
		SEGMENT_ANALYSIS_PROMPT: NO_SECONDARY_ASR_SEGMENT_ANALYSIS_PROMPT,
		ENHANCED_ANALYSIS_PROMPT: NO_SECONDARY_ASR_ENHANCED_ANALYSIS_PROMPT,
		MULTI_SEGMENT_ANALYSIS_PROMPT: NO_SECONDARY_ASR_MULTI_SEGMENT_ANALYSIS_PROMPT,
		MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT: NO_SECONDARY_ASR_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
	}
};

/**
 * Get prompts for a specific strategy
 */
export function getPrompts(strategy: PromptStrategy = 'wer_focused'): PromptSet {
	return PROMPT_STRATEGIES[strategy];
}

/**
 * Get available prompt strategies
 */
export function getAvailableStrategies(): PromptStrategy[] {
	return Object.keys(PROMPT_STRATEGIES) as PromptStrategy[];
}

// Default export for backwards compatibility
export const {
	SEGMENT_ANALYSIS_PROMPT,
	ENHANCED_ANALYSIS_PROMPT,
	MULTI_SEGMENT_ANALYSIS_PROMPT,
	MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} = getPrompts('wer_focused');

// Export individual prompt sets for direct access
export {
	WER_FOCUSED_SEGMENT_ANALYSIS_PROMPT,
	WER_FOCUSED_ENHANCED_ANALYSIS_PROMPT,
	WER_FOCUSED_MULTI_SEGMENT_ANALYSIS_PROMPT,
	WER_FOCUSED_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} from './wer_focused_analysis';

export {
	LEGACY_SEGMENT_ANALYSIS_PROMPT,
	LEGACY_ENHANCED_ANALYSIS_PROMPT,
	LEGACY_MULTI_SEGMENT_ANALYSIS_PROMPT,
	LEGACY_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} from './legacy_analysis';

export {
	NO_SECONDARY_ASR_SEGMENT_ANALYSIS_PROMPT,
	NO_SECONDARY_ASR_ENHANCED_ANALYSIS_PROMPT,
	NO_SECONDARY_ASR_MULTI_SEGMENT_ANALYSIS_PROMPT,
	NO_SECONDARY_ASR_MULTI_SEGMENT_ENHANCED_ANALYSIS_PROMPT
} from './no_secondary_asr_analysis';