import { prisma } from '$lib/db/client';
import { promises as fs } from 'fs';
import { error } from '@sveltejs/kit';
import docx from 'docx';
const { Packer } = docx;
import { toEditorDoc } from '$lib/helpers/converters/editorDoc';
import { buildTranscriptDocx } from '$lib/helpers/converters/docxFormat';
import { buildTranscriptOdt } from '$lib/helpers/converters/odtFormat';
import { toPlainText } from '$lib/helpers/converters/txtFormat';
import { toSRT } from '$lib/helpers/converters/srtFormat';
import { toTRS } from '$lib/helpers/converters/trsFormat';
import type { RequestHandler } from './$types';

const EXPORT_FORMATS = ['docx', 'odt', 'txt', 'srt', 'trs', 'json'] as const;
type ExportFormat = (typeof EXPORT_FORMATS)[number];

const MIME_TYPES: Record<ExportFormat, string> = {
	docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	odt: 'application/vnd.oasis.opendocument.text',
	txt: 'text/plain; charset=utf-8',
	srt: 'application/x-subrip; charset=utf-8',
	trs: 'application/xml; charset=utf-8',
	json: 'application/json; charset=utf-8'
};

function isExportFormat(value: string | null): value is ExportFormat {
	return value !== null && (EXPORT_FORMATS as readonly string[]).includes(value);
}

/** Drops the audio container extension so the export is named after the recording. */
function baseName(filename: string): string {
	const stripped = filename.replace(/\.[A-Za-z0-9]{1,5}$/, '');
	return stripped.trim() || 'transkriptsioon';
}

/**
 * Wraps generated bytes as a response body. The builders hand back a pooled Node
 * Buffer or a Uint8Array whose backing store TypeScript cannot prove is a plain
 * ArrayBuffer, so copy into one before handing it to Blob.
 */
function toBody(bytes: Uint8Array): Blob {
	const copy = new Uint8Array(bytes.byteLength);
	copy.set(bytes);
	return new Blob([copy.buffer]);
}

function contentDisposition(name: string): string {
	// Latin-1 fallback for clients that ignore RFC 5987, plus the real UTF-8 name.
	const ascii = name.replace(/[^\x20-\x7e]/g, '_').replace(/["\\]/g, '_');
	return `attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(name)}`;
}

export const GET: RequestHandler = async ({ params, url, locals }) => {
	const session = await locals.auth();
	if (!session || !session.user.id) {
		error(401, 'Not authenticated user');
	}

	const format = url.searchParams.get('format');
	if (!isExportFormat(format)) {
		error(400, 'unsupportedFormat');
	}

	const includeNames = url.searchParams.get('names') !== 'false';
	const includeTimeCodes = url.searchParams.get('times') === 'true';

	const file = await prisma.file.findUnique({
		where: { id: params.fileId },
		select: {
			filename: true,
			state: true,
			initialTranscriptionPath: true,
			User: { select: { id: true } }
		}
	});

	if (!file || file.User.id !== session.user.id) {
		error(404, 'fileNotFound');
	}

	if (!file.initialTranscriptionPath) {
		error(409, 'transcriptionNotReady');
	}

	let rawTranscription: string;
	try {
		rawTranscription = await fs.readFile(file.initialTranscriptionPath, 'utf8');
	} catch (readError) {
		console.log('Failed to read transcription for export', params.fileId, readError);
		error(409, 'transcriptionNotReady');
	}

	let doc;
	try {
		doc = toEditorDoc(rawTranscription);
	} catch (parseError) {
		console.log('Failed to parse transcription for export', params.fileId, parseError);
		error(500, 'transcriptionUnreadable');
	}

	const name = baseName(file.filename ?? '');
	let body: string | Blob;

	switch (format) {
		case 'docx':
			body = toBody(
				await Packer.toBuffer(
					buildTranscriptDocx(doc, { title: name, includeNames, includeTimeCodes })
				)
			);
			break;
		case 'odt':
			body = toBody(
				await buildTranscriptOdt(doc, { title: name, includeNames, includeTimeCodes })
			);
			break;
		case 'txt':
			body = toPlainText(doc, { includeNames, includeTimeCodes });
			break;
		case 'srt':
			body = toSRT(doc);
			break;
		case 'trs':
			body = toTRS(doc, file.filename ?? name);
			break;
		case 'json':
			body = JSON.stringify(doc);
			break;
	}

	return new Response(body, {
		status: 200,
		headers: {
			'content-type': MIME_TYPES[format],
			'content-disposition': contentDisposition(`${name}.${format}`),
			'cache-control': 'no-store'
		}
	});
};
